export const RESPONSE_PRIMARY_CATEGORIES = 'Home/RESPONSE_PRIMARY_CATEGORIES';
export const REQUEST_PRIMARY_CATEGORIES = 'Home/REQUEST_PRIMARY_CATEGORIES';
export const INCREMENT_VERSION = 'Home/INCREMENT_VERSION';
export const SET_MINUTES_BEFORE_TIME_SLOT_DEACTIVATION = 'Home/SET_MINUTES_BEFORE_TIME_SLOT_DEACTIVATION';
export const SET_TIME_SLOT_FULL_NOTIFICATION_DISABLE_TIME = 'Home/SET_TIME_SLOT_FULL_NOTIFICATION_DISABLE_TIME';
